general {
  # command to run when locking
  # lock before suspend
    lock_cmd = pidof hyprlock || hyprlock       
    before_sleep_cmd = loginctl lock-session    
}

listener {
  # 5min
  # lock screen
    timeout = 300                                
    on-timeout = loginctl lock-session          
    on-close = loginctl lock-session && systemctl suspend
}


